# actionscore/cs-sdk pipeline

trigger:
- master
- release-*

stages:
- stage: Build
  jobs:
  - job: 'build_projects'
    pool:
      vmImage: 'windows-2019'
    strategy:
      maxParallel: 2
      matrix:
        debug:
          configuration: debug
        release:
          configuration: release
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration $(Configuration)'
          projects: 'code.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          arguments: '--configuration $(Configuration)'
          projects: 'code.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          arguments: '--configuration $(Configuration)'
          packagesToPack: 'src/Microsoft.Actions.Actors/Microsoft.Actions.Actors.csproj'
          nobuild: true
          versioningScheme: 'off'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'bin/$(Configuration)'
- stage: Publish
  displayName: 'Publish Nuget Packages'
  dependsOn: Build
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: 'publish_edge_binaries'
    pool:
      vmImage: 'windows-2019'