# actionscore/cs-sdk pipeline

trigger:
- master
- release-*

stages:
- stage: Build
  jobs:
  - job: 'build_projects'
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'code.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'code.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          packagesToPack: 'src/Microsoft.Actions.Actors/Microsoft.Actions.Actors.csproj'
          nobuild: true
          versioningScheme: 'byBuildNumber'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'bin'
- stage: Publish
  displayName: 'Publish Nuget Packages'
  dependsOn: Build
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: 'publish_edge_binaries'
    pool:
      vmImage: 'windows-2019'